#!/bin/sh
# =============================================================================
# Entrypoint — wires Render's $PORT into nginx, generates a working
# /var/www/.env from the container's real environment, fixes storage
# permissions, and runs migrations.
# =============================================================================
# Why generate .env here?
#   Laravel reads `/var/www/.env` first, and only falls back to the actual
#   process environment if a key is missing. If Render's "Infrastructure"
#   tab has stale env vars (e.g. DB_CONNECTION=mysql from an earlier run),
#   they win over our render.yaml config. We rebuild .env every boot from
#   the *real* environment so we always have the correct production values.
# =============================================================================

set -eu

cd /var/www

PORT_VALUE="${PORT:-10000}"

# ---- 1. nginx listen port -------------------------------------------------
CONF="/etc/nginx/nginx.conf"
if [ -f "$CONF" ]; then
    sed -i "s|\${PORT}|${PORT_VALUE}|g" "$CONF"
    echo "[entrypoint] nginx will listen on 0.0.0.0:${PORT_VALUE}"
fi

# ---- 2. Generate /var/www/.env from the real environment -----------------
# We use simple shell expansion: ${VAR:-default} reads from the process
# environment if VAR is set, else uses the default. Single-quote values
# avoid any shell metacharacter surprises; values containing apostrophes
# are exceedingly unlikely in this environment block.
APP_NAME="${APP_NAME:-Madlog Store}"
APP_ENV="${APP_ENV:-production}"
APP_DEBUG="${APP_DEBUG:-false}"
APP_KEY="${APP_KEY:-}"
APP_URL="${APP_URL:-http://localhost:${PORT_VALUE}}"

DB_CONNECTION="${DB_CONNECTION:-pgsql}"
DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-5432}"
DB_DATABASE="${DB_DATABASE:-laravel}"
DB_USERNAME="${DB_USERNAME:-root}"
DB_PASSWORD="${DB_PASSWORD:-}"
DB_SSLMODE="${DB_SSLMODE:-prefer}"

SESSION_DRIVER="${SESSION_DRIVER:-database}"
SESSION_SECURE_COOKIE="${SESSION_SECURE_COOKIE:-true}"
SESSION_LIFETIME="${SESSION_LIFETIME:-120}"
CACHE_STORE="${CACHE_STORE:-database}"
QUEUE_CONNECTION="${QUEUE_CONNECTION:-sync}"

MAIL_MAILER="${MAIL_MAILER:-log}"
MAIL_FROM_ADDRESS="${MAIL_FROM_ADDRESS:-hello@madlogstore.test}"
MAIL_FROM_NAME="${MAIL_FROM_NAME:-${APP_NAME}}"

# Single-quote the value, escaping any single quotes by closing/reopening.
write_env() {
    key="$1"
    val="$2"
    # Replace ' with '\'' (POSIX-safe single-quote escape).
    escaped=$(printf '%s' "$val" | sed "s/'/'\\\\''/g")
    printf "%s='%s'\n" "$key" "$escaped"
}

{
    printf "# Auto-generated by docker/entrypoint.sh at %s.\n" "$(date -u +%FT%TZ)"
    printf "# Do NOT edit — changes are wiped on every container boot.\n"
    write_env APP_NAME          "$APP_NAME"
    write_env APP_ENV           "$APP_ENV"
    write_env APP_DEBUG         "$APP_DEBUG"
    write_env APP_KEY           "$APP_KEY"
    write_env APP_URL           "$APP_URL"
    write_env DB_CONNECTION     "$DB_CONNECTION"
    write_env DB_HOST           "$DB_HOST"
    write_env DB_PORT           "$DB_PORT"
    write_env DB_DATABASE       "$DB_DATABASE"
    write_env DB_USERNAME       "$DB_USERNAME"
    write_env DB_PASSWORD       "$DB_PASSWORD"
    write_env DB_SSLMODE        "$DB_SSLMODE"
    write_env SESSION_DRIVER    "$SESSION_DRIVER"
    write_env SESSION_SECURE_COOKIE "$SESSION_SECURE_COOKIE"
    write_env SESSION_LIFETIME  "$SESSION_LIFETIME"
    write_env CACHE_STORE       "$CACHE_STORE"
    write_env QUEUE_CONNECTION  "$QUEUE_CONNECTION"
    write_env LOG_CHANNEL       stderr
    write_env LOG_STACK         stderr
    write_env LOG_LEVEL         info
    write_env MAIL_MAILER       "$MAIL_MAILER"
    write_env MAIL_FROM_ADDRESS "$MAIL_FROM_ADDRESS"
    write_env MAIL_FROM_NAME    "$MAIL_FROM_NAME"
    write_env BROADCAST_CONNECTION log
    write_env FILESYSTEM_DISK   local
    write_env BCRYPT_ROUNDS     12
} > .env

# If APP_KEY is empty (e.g. the user removed generateValue from render.yaml
# and didn't set it manually), generate a fresh one now and persist it in
# the running container's .env so subsequent boots / sessions can decrypt
# cookies using the same key.
if [ -z "$APP_KEY" ]; then
    NEW_KEY=$(php artisan key:generate --show --no-interaction 2>/dev/null || true)
    if [ -n "$NEW_KEY" ]; then
        # Replace the placeholder line we just wrote with the real key.
        escaped=$(printf '%s' "$NEW_KEY" | sed "s/'/'\\\\''/g")
        sed -i "s|^APP_KEY=.*|APP_KEY='${escaped}'|" .env
        echo "[entrypoint] generated fresh APP_KEY"
    fi
fi

# ---- 3. Storage / cache permissions --------------------------------------
# php-fpm runs as root in this container, but storage/ may have been
# created by an earlier boot with different ownership, and we want
# Laravel's log writer to always be able to append.
mkdir -p storage/logs storage/framework/cache/data \
         storage/framework/sessions storage/framework/views \
         bootstrap/cache
chown -R root:root storage bootstrap/cache 2>/dev/null || true
chmod -R u+rwX,go+rwX storage bootstrap/cache 2>/dev/null || true
# Make sure the laravel.log file itself is writable (the file the
# original "Permission denied" error referenced).
touch storage/logs/laravel.log
chmod 0666 storage/logs/laravel.log

# ---- 4. Run migrations ----------------------------------------------------
if [ "${RUN_MIGRATIONS:-1}" = "1" ]; then
    echo "[entrypoint] running database migrations"
    php artisan migrate --force --no-interaction || {
        echo "[entrypoint] migration failed; continuing to start web server anyway"
    }
fi

# ---- 5. Clear any cached config that was baked at build time -------------
# config:cache / route:cache embed env values into bootstrap files that
# would otherwise win over .env. Drop them so Laravel re-reads .env.
rm -f bootstrap/cache/config.php bootstrap/cache/routes-v7.php \
      bootstrap/cache/services.php 2>/dev/null || true

exec "$@"
